<?php
/**
* Digit Software Solutions..
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
*
* @category   Dss
* @package    Dss_HtmlSiteMap
* @author     Extension Team
* @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
*/
?>
<?php
/**
 * SEO Toolbar template
 *
 * @var $block Dss\HtmlSiteMap\Block\CategoryCollection
 */
?>
<?php
$helper = $block->getHelper();

//CMS and Category Link
$categories = $block->getCategoryCollection($isActive = true, $level = false, $sortBy = false, $pageSize = false);
$categoryHelper = $block->getCategoryHelper();
$categoryDisable = $helper->getCategoryDisable();
$titleCategory = $helper->titleCategory();
$titleCms = $helper->titleCms();
$enableCms = $helper->isEnableCms();
$enableCategory = $helper->isEnableCategory();
$cmsLink = $helper->getCmsLink();
$cmsLink = ",," . $cmsLink . ",";
$categoryDisable = ",," . $categoryDisable . ",";

?>
<div class="col-dss-1">
    <?php
    if ($enableCategory): ?>
        <div class="col-dss-2">
            <h2 class="dss_h2"><?= /* @noEscape */ $titleCategory; ?></h2>
            <?php foreach ($categories as $category):
                if (!$category->getIsActive() || (int)$category->getData('excluded_html_sitemap') === 1) {
                    continue;
                } ?>
                <?php
                $categoryString = (string)$category->getId();
                $categoryString = "," . $categoryString . ",";
                $categoryStringValidate = strpos($categoryDisable, $categoryString);
                if ($categoryStringValidate == false): ?>
                <div class="dss_h3">
                    <?= /* @noEscape */ $category->getName()?>
                </div>
                    <?php
                        $setAllCategories = $block->getAllCategories($category, $categoryDisable);
                       /* @noEscape */ echo $setAllCategories; ?>
                <?php endif; ?>
            <?php endforeach;
            ?>
        </div>
        <?php
    endif; ?>
    <?php
    if ($enableCms): ?>
        <div class="col-dss-2">
            <h2 class="dss_h2"><?= /* @noEscape */ $titleCms; ?></h2>
        <?php
        $getCMS = $block->getCmsPages();
        foreach ($getCMS as $item => $value) {
            if (!$value->getIsActive()) {
                continue;
            }
            $stringItem = (string)$item;
            $stringItem = "," . $stringItem . ",";
            $stringItemValidate = strpos($cmsLink, $stringItem);
            if ($stringItemValidate == false) {
               /* @noEscape */ echo '
                    <h3 class="dss_product_list">
                        <a href="' . $block->getBaseUrl() . $value->getIdentifier() . '/"
                            title = "' . $value->getTitle() . '"">' . $value->getTitle() . '</a>
                    </h3>';
            }
        } ?>
        </div>
        <?php
    endif; ?>
</div>