<?php
/**
* Digit Software Solutions..
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
*
* @category   Dss
* @package    Dss_HtmlSiteMap
* @author     Extension Team
* @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
*/
?>
<?php
/**
 * SEO Toolbar template
 *
 * @var $block Dss\HtmlSiteMap\Block\ItemsCollection
 */
?>
<?php
$helper = $block->getHelper();
$baseUrl = $helper->getBaseUrl();
$getEnable = $helper->isEnable();
$urlKey = $helper->getModuleRoute();
$titleSiteMap = $helper->getTitleSiteMap();
$showLinkAt = $helper->getShowLinkAt();
?>
<?php if ($getEnable && $showLinkAt === 'top'): ?>
    <li>
        <a href="<?= /* @noEscape */  $baseUrl . $urlKey; ?>">
            <?= /* @noEscape */  $escaper->escapeHtml($titleSiteMap); ?>
        </a>
    </li>
    <?php
endif;
