<?php
   /**
    * Digit Software Solutions..
    *
    * NOTICE OF LICENSE
    *
    * This source file is subject to the EULA
    * that is bundled with this package in the file LICENSE.txt.
    *
    * @category   Dss
    * @package    Dss_HtmlSiteMap
    * @author     Extension Team
    * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
    */
?>
<?php
/**
 * SEO Toolbar template
 *
 * @var $block Dss\HtmlSiteMap\Block\ProductCollection
 */
?>
<?php
$helper = $block->getHelper();

//Product Link
$enableProduct = $helper->isEnableProduct();
$titleProduct = $helper->titleProduct();

if ($enableProduct): ?>
    <h2 class="dss_h2"><?= $escaper->escapeHtml(__($titleProduct)) ?></h2>
    <div class="dss_site_map_grid">
        <?php
        $productCollection = $block->getProductCollection();
        foreach ($productCollection as $product): ?>
            <?= $escaper->escapeHtml(__($product->getData("id")));
            echo '<div class="col-dss-3">
                    <h3 class="dss_product_list">
                    <a href="'.$escaper->escapeHtml(__($product->getUrlModel()->getUrl($product))).'"
                    title = "'.$escaper->escapeHtml(__($product->getName())).'"
                    >'.$escaper->escapeHtml(__($product->getName())).'</a>
                    </h3>
                </div>';
        endforeach; ?>
    </div>
<?php endif; ?>