
<?php
/**
 * Digit Software Solutions..
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category   Dss
 * @package    Dss_SeoCore
 * @author     Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<?php
/**
 * Seo Core Validate Bing and Google
 * @var $block Dss\SeoCore\Block\Validate
 */
?>
<?php
$dataHelper = $block->getHelper();
$googleSearchConsoleValidate = $dataHelper->getGoogleVerification();
$bingValidate = $dataHelper->getBingVerification();
if ($googleSearchConsoleValidate !== '' && $googleSearchConsoleValidate !== null && $googleSearchConsoleValidate): ?>
    <meta name="google-site-verification" content="<?= $escaper->escapeHtml($googleSearchConsoleValidate); ?>" />
<?php endif; ?>

<?php if ($bingValidate !== '' && $bingValidate !== null && $bingValidate): ?>
    <meta name="msvalidate.01" content="<?= $escaper->escapeHtml($bingValidate); ?>" />
<?php endif; ?>
